//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAC.Library.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_variable_prioritaria
    {
        public System.Guid Id { get; set; }
        public string nombreVariable { get; set; }
        public string valorVariable { get; set; }
        public string valorUmbral { get; set; }
        public System.Guid tbl_paciente_prioritario_id { get; set; }
    
        public virtual tbl_paciente_prioritario tbl_paciente_prioritario { get; set; }
    }
}
