//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAC.Library.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_archivo_cac
    {
        public tbl_archivo_cac()
        {
            this.tbl_paciente_prioritario = new HashSet<tbl_paciente_prioritario>();
            this.tbl_validacion_archivo = new HashSet<tbl_validacion_archivo>();
            this.tbl_cac = new HashSet<tbl_cac>();
        }
    
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string tamano { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int numFilasImportadas { get; set; }
        public string urlArchivo { get; set; }
        public System.Guid idUsuario { get; set; }
    
        public virtual tbl_usuario tbl_usuario { get; set; }
        public virtual ICollection<tbl_paciente_prioritario> tbl_paciente_prioritario { get; set; }
        public virtual ICollection<tbl_validacion_archivo> tbl_validacion_archivo { get; set; }
        public virtual ICollection<tbl_cac> tbl_cac { get; set; }
    }
}
