//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAC.Library.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario_rol
    {
        public System.Guid id { get; set; }
        public System.Guid idRol { get; set; }
        public System.Guid idUsuario { get; set; }
    
        public virtual tbl_rol tbl_rol { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
