//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAC.Library.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_paciente_prioritario
    {
        public tbl_paciente_prioritario()
        {
            this.tbl_variable_prioritaria = new HashSet<tbl_variable_prioritaria>();
            this.tbl_variable_desactualizada = new HashSet<tbl_variable_desactualizada>();
        }
    
        public System.Guid id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string cedula { get; set; }
        public string numContacto { get; set; }
        public System.Guid idArchivo { get; set; }
    
        public virtual tbl_archivo_cac tbl_archivo_cac { get; set; }
        public virtual ICollection<tbl_variable_prioritaria> tbl_variable_prioritaria { get; set; }
        public virtual ICollection<tbl_variable_desactualizada> tbl_variable_desactualizada { get; set; }
    }
}
