//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAC.Library.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cac
    {
        public System.Guid id { get; set; }
        public System.Guid idArchivo { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string tipoIdentificacion { get; set; }
        public string numIdentificacion { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string diagHiperArterial { get; set; }
        public System.DateTime fecDiagHiperArterial { get; set; }
        public string diagDiabetesMellitus { get; set; }
        public System.DateTime fecDiadDiabetesMellitus { get; set; }
        public string etiologiaCAC { get; set; }
        public string PesoKG { get; set; }
        public string tallaCtms { get; set; }
        public string tensionArtSistolica { get; set; }
        public string tensionArtDiastolica { get; set; }
        public string creatinina { get; set; }
        public System.DateTime fecUltimaCreatinina { get; set; }
        public string hemoglobinaGlicosilada { get; set; }
        public System.DateTime fecHemoGlicosilada { get; set; }
        public string albuminuria { get; set; }
        public System.DateTime fecUltimaAlbuminuria { get; set; }
        public string creatinuria { get; set; }
        public System.DateTime fecUltimaCreatinuria { get; set; }
        public string LDL { get; set; }
        public System.DateTime fecUltimaLDL { get; set; }
        public string PTH { get; set; }
        public System.DateTime fechaPTH { get; set; }
        public string tasaFiltracionGlomerular { get; set; }
        public string diagEnferRenalCronicoERC { get; set; }
        public string estadioERC { get; set; }
        public System.Guid idOrganizacion { get; set; }
    
        public virtual tbl_archivo_cac tbl_archivo_cac { get; set; }
    }
}
