//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CACWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cac/v1.
        /// </summary>
        public static string API_VERSION_FILEUPLOAD {
            get {
                return ResourceManager.GetString("API_VERSION_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cac/v1/indicadores.
        /// </summary>
        public static string API_VERSION_INDICADORES {
            get {
                return ResourceManager.GetString("API_VERSION_INDICADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/cac/v1/indicadorestotales.
        /// </summary>
        public static string API_VERSION_INDICADORES_TOTALES {
            get {
                return ResourceManager.GetString("API_VERSION_INDICADORES_TOTALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cac/get.
        /// </summary>
        public static string CAC_GETFILEBYID_GET {
            get {
                return ResourceManager.GetString("CAC_GETFILEBYID_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file/listfilebyuser.
        /// </summary>
        public static string FILE_LISTBYUSER_GET {
            get {
                return ResourceManager.GetString("FILE_LISTBYUSER_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file/validatePriorityPatient.
        /// </summary>
        public static string FILE_VALIDATE_PRIORITY_PATIENT_POST {
            get {
                return ResourceManager.GetString("FILE_VALIDATE_PRIORITY_PATIENT_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file/validator.
        /// </summary>
        public static string FILE_VALIDATOR_POST {
            get {
                return ResourceManager.GetString("FILE_VALIDATOR_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file/validator2.
        /// </summary>
        public static string FILE_VALIDATOR_TESTING_POST {
            get {
                return ResourceManager.GetString("FILE_VALIDATOR_TESTING_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIREBASE_API_KEY {
            get {
                return ResourceManager.GetString("FIREBASE_API_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIREBASE_AUTH_DOMAIN {
            get {
                return ResourceManager.GetString("FIREBASE_AUTH_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIREBASE_DATABASE_URL {
            get {
                return ResourceManager.GetString("FIREBASE_DATABASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIREBASE_MESSAGING_SENDER_ID {
            get {
                return ResourceManager.GetString("FIREBASE_MESSAGING_SENDER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIREBASE_STORAGE_BUCKET {
            get {
                return ResourceManager.GetString("FIREBASE_STORAGE_BUCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getAlbuminuria.
        /// </summary>
        public static string INDICADORES_getAlbuminuria {
            get {
                return ResourceManager.GetString("INDICADORES_getAlbuminuria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getControlDiabetesMellitus.
        /// </summary>
        public static string INDICADORES_getControlDiabetesMellitus {
            get {
                return ResourceManager.GetString("INDICADORES_getControlDiabetesMellitus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getControlHipertensionArterial.
        /// </summary>
        public static string INDICADORES_getControlHipertensionArterial {
            get {
                return ResourceManager.GetString("INDICADORES_getControlHipertensionArterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getControlLDL.
        /// </summary>
        public static string INDICADORES_getControlLDL {
            get {
                return ResourceManager.GetString("INDICADORES_getControlLDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getControlPTH3.
        /// </summary>
        public static string INDICADORES_getControlPTH3 {
            get {
                return ResourceManager.GetString("INDICADORES_getControlPTH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getControlPTH4.
        /// </summary>
        public static string INDICADORES_getControlPTH4 {
            get {
                return ResourceManager.GetString("INDICADORES_getControlPTH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getControlPTH5.
        /// </summary>
        public static string INDICADORES_getControlPTH5 {
            get {
                return ResourceManager.GetString("INDICADORES_getControlPTH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getCreatinina.
        /// </summary>
        public static string INDICADORES_getCreatinina {
            get {
                return ResourceManager.GetString("INDICADORES_getCreatinina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getHba1c.
        /// </summary>
        public static string INDICADORES_getHba1c {
            get {
                return ResourceManager.GetString("INDICADORES_getHba1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getHipertensionArterial.
        /// </summary>
        public static string INDICADORES_getHipertensionArterial {
            get {
                return ResourceManager.GetString("INDICADORES_getHipertensionArterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getLDL.
        /// </summary>
        public static string INDICADORES_getLDL {
            get {
                return ResourceManager.GetString("INDICADORES_getLDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMedicionAlbuminuria.
        /// </summary>
        public static string INDICADORES_getMedicionAlbuminuria {
            get {
                return ResourceManager.GetString("INDICADORES_getMedicionAlbuminuria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMedicionCreatina.
        /// </summary>
        public static string INDICADORES_getMedicionCreatina {
            get {
                return ResourceManager.GetString("INDICADORES_getMedicionCreatina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMedicionHbA1c.
        /// </summary>
        public static string INDICADORES_getMedicionHbA1c {
            get {
                return ResourceManager.GetString("INDICADORES_getMedicionHbA1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMedicionLDL.
        /// </summary>
        public static string INDICADORES_getMedicionLDL {
            get {
                return ResourceManager.GetString("INDICADORES_getMedicionLDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMedicionPTH3.
        /// </summary>
        public static string INDICADORES_getMedicionPTH3 {
            get {
                return ResourceManager.GetString("INDICADORES_getMedicionPTH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getProgEnfRenal.
        /// </summary>
        public static string INDICADORES_getProgEnfRenal {
            get {
                return ResourceManager.GetString("INDICADORES_getProgEnfRenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getProgresionRenal.
        /// </summary>
        public static string INDICADORES_getProgresionRenal {
            get {
                return ResourceManager.GetString("INDICADORES_getProgresionRenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getPTH3.
        /// </summary>
        public static string INDICADORES_getPTH3 {
            get {
                return ResourceManager.GetString("INDICADORES_getPTH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getPTH4.
        /// </summary>
        public static string INDICADORES_getPTH4 {
            get {
                return ResourceManager.GetString("INDICADORES_getPTH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getPTH5.
        /// </summary>
        public static string INDICADORES_getPTH5 {
            get {
                return ResourceManager.GetString("INDICADORES_getPTH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMedicionPTH4.
        /// </summary>
        public static string INDICADORES_getrMedicionPTH4 {
            get {
                return ResourceManager.GetString("INDICADORES_getrMedicionPTH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMedicionPTH5.
        /// </summary>
        public static string INDICADORES_getrMedicionPTH5 {
            get {
                return ResourceManager.GetString("INDICADORES_getrMedicionPTH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prioritypatient/listbyfile.
        /// </summary>
        public static string PRIORITYPATIENT_LISTBYFILE_GET {
            get {
                return ResourceManager.GetString("PRIORITYPATIENT_LISTBYFILE_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/TempFiles.
        /// </summary>
        public static string TemporalServerFolder {
            get {
                return ResourceManager.GetString("TemporalServerFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:10090.
        /// </summary>
        public static string URL_LOCAL_FILEUPLOAD {
            get {
                return ResourceManager.GetString("URL_LOCAL_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:16730.
        /// </summary>
        public static string URL_LOCAL_INDICADORES {
            get {
                return ResourceManager.GetString("URL_LOCAL_INDICADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string URL_PRODUCTION_FILEUPLOAD {
            get {
                return ResourceManager.GetString("URL_PRODUCTION_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string URL_PRODUCTION_INDICADORES {
            get {
                return ResourceManager.GetString("URL_PRODUCTION_INDICADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string URL_TESTING_FILEUPLOAD {
            get {
                return ResourceManager.GetString("URL_TESTING_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string URL_TESTING_INDICADORES {
            get {
                return ResourceManager.GetString("URL_TESTING_INDICADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/add.
        /// </summary>
        public static string USER_ADD_POST {
            get {
                return ResourceManager.GetString("USER_ADD_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/get.
        /// </summary>
        public static string USER_GET_GET {
            get {
                return ResourceManager.GetString("USER_GET_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/getbyemail.
        /// </summary>
        public static string USER_GETBYEMAIL_GET {
            get {
                return ResourceManager.GetString("USER_GETBYEMAIL_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/list.
        /// </summary>
        public static string USER_LIST_GET {
            get {
                return ResourceManager.GetString("USER_LIST_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/listorganization.
        /// </summary>
        public static string USER_LIST_ORGANIZATION_GET {
            get {
                return ResourceManager.GetString("USER_LIST_ORGANIZATION_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/listrole.
        /// </summary>
        public static string USER_LIST_ROLE_GET {
            get {
                return ResourceManager.GetString("USER_LIST_ROLE_GET", resourceCulture);
            }
        }
    }
}
